version: "3.9"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    networks:
      - djangonetwork
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - env/db.env
  django:
    build: .
    container_name: django
    command: bash -c "./manage.py migrate && exec ./manage.py runserver 0.0.0.0:8000;"
    networks:
      - djangonetwork
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - env/.env
      - env/db.env
    depends_on:
      - pgdb
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    volumes:
      - .showroom-redis:/data
  celery:
    build: .
    container_name: celery
    restart: always
    command: celery -A showroom worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - env/redis.env
    depends_on:
      - pgdb
      - redis
      - django
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower
    env_file:
      - env/redis.env
    depends_on:
      - celery
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/data
volumes:
  pg_data:
    driver: local
  flower_data:
    driver: local
networks:
  djangonetwork:
    driver: bridge