version: "3.9"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    networks:
      - djangonetwork
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - env/db.env
  django:
    build: .
    container_name: django
    command: bash -c "./showroom/manage.py migrate && exec ./showroom/manage.py runserver 0.0.0.0:8000;"
    networks:
      - djangonetwork
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - env/.env
      - env/db.env
    depends_on:
      - pgdb
volumes:
  pg_data:
    driver: local
networks:
  djangonetwork:
    driver: bridge