version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - env/db.env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./showroom/manage.py migrate && exec ./showroom/manage.py runserver 0.0.0.0:8000; "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - env/.env
      - env/db.env
    depends_on:
      - db